version: '3.9'
services:
  app:
    build:
      context: .
      target: runner
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: unless-stopped
  app-dev:
    build:
      context: .
      target: base
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: development
    command: pnpm dev
